"""add_display_property_to_entity_types

Revision ID: 8c1fc8dcaa1c
Revises: 0302c0057ecc
Create Date: 2026-04-21 14:21:56.169158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1fc8dcaa1c'
down_revision: Union[str, Sequence[str], None] = '0302c0057ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_types', sa.Column('display_property', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_types', 'display_property')
    # ### end Alembic commands ###
